---

- hosts: 192.168.33.11
  remote_user: root
  tasks:
    - include: apache-tasks.yml
  handlers:
    - include: apache-handlers.yml

- hosts: 192.168.33.12
  remote_user: root
  tasks:
    - include: nginx-tasks.yml
  handlers:
    - include: nginx-handlers.yml

...