---
- hosts: 192.168.33.11
  remote_user: root
  tasks:
    - name: Install Apache2 package
      apt: name=apache2 state=present
    - name: Ensure Apache2 service is running
      service: name=apache2 state=started enabled=yes
- hosts: 192.168.33.12
  remote_user: root
  tasks: 
     - name: Uninstall Apache2
       apt: name=apache2 state=absent
     - name: Install haproxy load balanced
       apt: name=haproxy state=present
...
