---

mysql_packages:
  - python-selinux
  - python-mysqldb
  - mysql-server

mysql_service: mysql

mysql_conf_dir: "/etc/mysql"

mysql_port: 3306
mysql_bind_address: "0.0.0.0"
mysql_root_db_pass: root

mysql_db:
  - name: "{{ dbname }}""

mysql_users:
  - name: wpuser
    pass: wppass
    priv: "*.*:ALL"