---

php_packages:
  - php5
  - libapache2-mod-php5
  - php5-mysql
  - php5-curl
  - php5-gd
  - php5-intl
  - php-pear
  - php5-imap
  - php5-mcrypt
  - php5-memcache
  - php5-pspell
  - php5-recode
  - php5-tidy
  - php5-xmlrpc
  - php5-xsl
  - php-gettext